# Generated by Django 6.0 on 2026-01-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(choices=[('informatique', 'Département Informatique'), ('mathematiques', 'Département Mathématiques'), ('physique', 'Département Physique'), ('chimie', 'Département Chimie'), ('biologie', 'Département Biologie'), ('genie_civil', 'Département Génie Civil'), ('genie_electrique', 'Département Génie Électrique'), ('genie_mecanique', 'Département Génie Mécanique'), ('economie', 'Département Économie et Gestion'), ('langues', 'Département Langues et Communication'), ('sciences_juridiques', 'Département Sciences Juridiques'), ('sciences_terre', 'Département Sciences de la Terre')], max_length=100, verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(choices=[('informatique_generale', 'Informatique Générale'), ('intelligence_artificielle', 'Intelligence Artificielle'), ('reseaux_securite', 'Réseaux et Sécurité'), ('genie_logiciel', 'Génie Logiciel'), ('systemes_information', "Systèmes d'Information"), ('science_donnees', 'Science des Données'), ('mathematiques_appliquees', 'Mathématiques Appliquées'), ('mathematiques_pures', 'Mathématiques Pures'), ('statistiques', 'Statistiques'), ('recherche_operationnelle', 'Recherche Opérationnelle'), ('physique_generale', 'Physique Générale'), ('physique_nucleaire', 'Physique Nucléaire'), ('physique_theorique', 'Physique Théorique'), ('electronique', 'Électronique'), ('optique', 'Optique'), ('chimie_organique', 'Chimie Organique'), ('chimie_inorganique', 'Chimie Inorganique'), ('chimie_analytique', 'Chimie Analytique'), ('chimie_industrielle', 'Chimie Industrielle'), ('biologie_moleculaire', 'Biologie Moléculaire'), ('genetique', 'Génétique'), ('ecologie', 'Écologie'), ('microbiologie', 'Microbiologie'), ('genie_civil', 'Génie Civil'), ('genie_electrique', 'Génie Électrique'), ('genie_mecanique', 'Génie Mécanique'), ('automatique', 'Automatique'), ('economie', 'Économie'), ('finance', 'Finance'), ('management', 'Management'), ('comptabilite', 'Comptabilité'), ('francais', 'Français'), ('anglais', 'Anglais'), ('arabe', 'Arabe'), ('autre', 'Autre')], max_length=100, verbose_name='Spécialité'),
        ),
    ]
