# Generated by Django 6.0 on 2026-01-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacher_field_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.EmailField(blank=True, help_text="Email institutionnel de l'étudiant", max_length=254, null=True, verbose_name='Email Étudiant'),
        ),
    ]
