# Generated by Django 6.0 on 2026-01-07 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacher_field_choices'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='capacity',
            field=models.PositiveIntegerField(default=100, help_text="Nombre maximum d'étudiants", verbose_name='Capacité'),
        ),
        migrations.AddField(
            model_name='program',
            name='program_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_programs', to='accounts.teacher', verbose_name='Chef de Filière'),
        ),
    ]
