# Generated by Django 6.0 on 2026-01-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_program_capacity_program_program_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='icon',
            field=models.CharField(default='fas fa-tools', max_length=50, verbose_name='Icône'),
        ),
    ]
