# Generated by Django 6.0 on 2026-01-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_equipment_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='department',
            field=models.CharField(choices=[('mathematiques_informatique', 'Département de Mathématiques et Informatique'), ('physique', 'Département de Physique'), ('chimie', 'Département de Chimie'), ('biologie', 'Département de Biologie'), ('geologie', 'Département de Géologie'), ('sciences_terre', 'Département de Sciences de la Terre')], max_length=100, verbose_name='Département'),
        ),
    ]
