# Generated by Django 6.0 on 2026-01-06 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReservationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_type', models.CharField(choices=[('teacher', 'Enseignant'), ('association', 'Association')], max_length=20, verbose_name='Type de demandeur')),
                ('requested_datetime', models.DateTimeField(verbose_name='Date et heure')),
                ('duration', models.IntegerField(verbose_name='Durée (heures)')),
                ('reason', models.TextField(verbose_name='Motif')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20, verbose_name='Statut')),
                ('is_exam', models.BooleanField(default=False, verbose_name='Pour un examen')),
                ('admin_notes', models.TextField(blank=True, verbose_name="Notes de l'administrateur")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_requests', to='accounts.association', verbose_name='Association')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_requests', to='core.room', verbose_name='Salle')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_requests', to='accounts.teacher', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Demande de Réservation',
                'verbose_name_plural': 'Demandes de Réservation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('cours', 'Cours'), ('td', 'TD'), ('tp', 'TP'), ('examen', 'Examen')], max_length=20, verbose_name='Type')),
                ('subject', models.CharField(max_length=200, verbose_name='Matière')),
                ('start_datetime', models.DateTimeField(verbose_name='Début')),
                ('end_datetime', models.DateTimeField(verbose_name='Fin')),
                ('is_exam', models.BooleanField(default=False, verbose_name='Est un examen')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Validée')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('groups', models.ManyToManyField(related_name='sessions', to='core.group', verbose_name='Groupes')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.room', verbose_name='Salle')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.teacher', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Séance',
                'verbose_name_plural': 'Séances',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='TeacherUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Début')),
                ('end_datetime', models.DateTimeField(verbose_name='Fin')),
                ('reason', models.TextField(verbose_name='Raison')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Récurrent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='accounts.teacher', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Indisponibilité Enseignant',
                'verbose_name_plural': 'Indisponibilités Enseignants',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=10, verbose_name='Année universitaire')),
                ('semester', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2')], max_length=20, verbose_name='Semestre')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='core.program', verbose_name='Filière')),
                ('sessions', models.ManyToManyField(blank=True, related_name='timetables', to='scheduling.session', verbose_name='Séances')),
            ],
            options={
                'verbose_name': 'Emploi du Temps',
                'verbose_name_plural': 'Emplois du Temps',
                'unique_together': {('program', 'academic_year', 'semester')},
            },
        ),
    ]
