# Generated by Django 6.0 on 2026-01-06 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreservationrequest',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de fin'),
        ),
        migrations.AddField(
            model_name='roomreservationrequest',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Sélectionnez la filière pour cette réservation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_requests', to='core.program', verbose_name='Filière concernée'),
        ),
        migrations.AddField(
            model_name='roomreservationrequest',
            name='reservation_type',
            field=models.CharField(choices=[('recurring', "Séance Hebdomadaire (Modifie l'emploi du temps)"), ('one_time', 'Séance Ponctuelle (Rattrapage/Révision)')], default='one_time', max_length=20, verbose_name='Type de réservation'),
        ),
        migrations.AddField(
            model_name='roomreservationrequest',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de début'),
        ),
        migrations.AddField(
            model_name='roomreservationrequest',
            name='subject',
            field=models.CharField(blank=True, help_text='Ex: Algèbre Linéaire, Révision Chimie', max_length=200, verbose_name='Matière/Sujet'),
        ),
        migrations.AddField(
            model_name='session',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Séance récurrente'),
        ),
        migrations.AddField(
            model_name='session',
            name='parent_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_sessions', to='scheduling.roomreservationrequest', verbose_name="Réservation d'origine"),
        ),
        migrations.AlterField(
            model_name='roomreservationrequest',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée (heures) (ancien)'),
        ),
        migrations.AlterField(
            model_name='roomreservationrequest',
            name='requested_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et heure (ancien)'),
        ),
    ]
