# Generated by Django 6.0 on 2026-01-11 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_student_email'),
        ('core', '0004_add_department_choices'),
        ('scheduling', '0002_roomreservationrequest_end_datetime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['-created_at'], 'verbose_name': 'Emploi du Temps', 'verbose_name_plural': 'Emplois du Temps'},
        ),
        migrations.AddField(
            model_name='timetable',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timetables', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='is_generated',
            field=models.BooleanField(default=False, verbose_name='Généré automatiquement'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='study_groups',
            field=models.ManyToManyField(blank=True, related_name='timetables', to='core.group', verbose_name="Groupes d'étude"),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la matière')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('session_type', models.CharField(choices=[('cours', 'Cours Magistral'), ('td', 'Travaux Dirigés'), ('tp', 'Travaux Pratiques')], default='cours', max_length=20, verbose_name='Type de séance')),
                ('hours_per_week', models.DecimalField(decimal_places=1, default=1.5, max_digits=4, verbose_name='Heures par semaine')),
                ('max_hours_per_day', models.DecimalField(decimal_places=1, default=3.0, max_digits=3, verbose_name='Max heures par jour')),
                ('requires_lab', models.BooleanField(default=False, verbose_name='Nécessite un laboratoire')),
                ('color', models.CharField(default='#8b5cf6', max_length=7, verbose_name="Couleur d'affichage")),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.program', verbose_name='Filière')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='accounts.teacher', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['program', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Lundi'), ('TUE', 'Mardi'), ('WED', 'Mercredi'), ('THU', 'Jeudi'), ('FRI', 'Vendredi'), ('SAT', 'Samedi')], max_length=3, verbose_name='Jour')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('slot_order', models.IntegerField(default=1, verbose_name='Ordre du créneau')),
            ],
            options={
                'verbose_name': 'Créneau Horaire',
                'verbose_name_plural': 'Créneaux Horaires',
                'ordering': ['day_of_week', 'slot_order'],
                'unique_together': {('day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
