# Generated by Django 6.0 on 2026-01-14 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_student_email'),
        ('core', '0004_add_department_choices'),
        ('scheduling', '0003_alter_timetable_options_timetable_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['slot_number'], 'verbose_name': 'Créneau Horaire', 'verbose_name_plural': 'Créneaux Horaires'},
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='slot_number',
            field=models.IntegerField(default=1, unique=True, verbose_name='Numéro du créneau'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='slot_order',
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Lundi'), ('TUE', 'Mardi'), ('WED', 'Mercredi'), ('THU', 'Jeudi'), ('FRI', 'Vendredi'), ('SAT', 'Samedi')], max_length=3, verbose_name='Jour')),
                ('session_type', models.CharField(choices=[('cours', 'Cours'), ('td', 'TD'), ('tp', 'TP')], default='cours', max_length=20, verbose_name='Type de séance')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='core.room', verbose_name='Salle')),
                ('study_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='core.group', verbose_name='Groupe')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='scheduling.subject', verbose_name='Matière')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='accounts.teacher', verbose_name='Enseignant')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scheduling.timeslot', verbose_name='Créneau horaire')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scheduling.timetable', verbose_name='Emploi du temps')),
            ],
            options={
                'verbose_name': "Entrée d'emploi du temps",
                'verbose_name_plural': "Entrées d'emploi du temps",
                'ordering': ['day_of_week', 'time_slot__slot_number'],
                'unique_together': {('timetable', 'day_of_week', 'time_slot', 'study_group')},
            },
        ),
    ]
