# Generated by Django 6.0 on 2026-01-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_department_choices'),
        ('scheduling', '0004_alter_timeslot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['program', 'semester', 'code'], 'verbose_name': 'Matière', 'verbose_name_plural': 'Matières'},
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')], default=1, verbose_name='Semestre'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='hours_per_week',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=4, verbose_name='Heures par semaine'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('code', 'program', 'semester')},
        ),
    ]
