# Generated by Django 6.0 on 2026-01-14 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_department_choices'),
        ('scheduling', '0005_add_subject_semester_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subject',
            name='sessions_cours',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de séances de cours par semaine', verbose_name='Séances COURS'),
        ),
        migrations.AddField(
            model_name='subject',
            name='sessions_td',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de séances de TD par semaine', verbose_name='Séances TD'),
        ),
        migrations.AddField(
            model_name='subject',
            name='sessions_tp',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de séances de TP par semaine', verbose_name='Séances TP'),
        ),
        migrations.AddField(
            model_name='subject',
            name='timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inline_subjects', to='scheduling.timetable', verbose_name='Emploi du temps'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.program', verbose_name='Filière'),
        ),
    ]
