# Generated by Django 6.0 on 2026-01-31 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_student_email'),
        ('scheduling', '0006_add_subject_session_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_change', models.TextField(help_text='Décrivez le changement souhaité (ex: Déplacer le cours du Lundi 8h au Mardi 10h)', verbose_name='Changement souhaité')),
                ('reason', models.TextField(blank=True, verbose_name='Justification')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('completed', 'Traitée')], default='pending', max_length=20, verbose_name='Statut')),
                ('admin_notes', models.TextField(blank=True, verbose_name="Notes de l'administration")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('current_entry', models.ForeignKey(blank=True, help_text='Si la demande concerne une séance précise', null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.timetableentry', verbose_name='Séance actuelle')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.subject', verbose_name='Matière concernée')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_change_requests', to='accounts.teacher', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Demande de changement',
                'verbose_name_plural': 'Demandes de changement',
                'ordering': ['-created_at'],
            },
        ),
    ]
