# Generated by Django 6.0 on 2026-02-13 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_timetablechangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='event_type',
            field=models.CharField(choices=[('recurring', 'Séance Récurrente'), ('one_off', 'Séance Ponctuelle')], default='recurring', max_length=20, verbose_name="Type d'événement"),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='is_exam',
            field=models.BooleanField(default=False, verbose_name='Examen'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='source_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='scheduling.roomreservationrequest', verbose_name='Réservation source'),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='session_type',
            field=models.CharField(choices=[('cours', 'Cours'), ('td', 'TD'), ('tp', 'TP'), ('exam', 'Examen')], default='cours', max_length=20, verbose_name='Type de séance'),
        ),
    ]
