# Generated by Django 6.0 on 2026-01-06 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('reservation_approved', 'Réservation Approuvée'), ('reservation_rejected', 'Réservation Rejetée'), ('exam_scheduled', 'Examen Programmé'), ('timetable_updated', 'Emploi du Temps Modifié'), ('room_changed', 'Salle Modifiée'), ('session_cancelled', 'Séance Annulée'), ('contact_received', 'Message Reçu'), ('association_approved', 'Association Approuvée'), ('general', 'Notification Générale')], max_length=50, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True, verbose_name="Type d'objet lié")),
                ('related_object_id', models.IntegerField(blank=True, null=True, verbose_name="ID de l'objet lié")),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
