# Generated by Django 6.0 on 2026-01-27 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reservation_pending', 'Nouvelle Demande de Réservation'), ('reservation_approved', 'Réservation Approuvée'), ('reservation_rejected', 'Réservation Rejetée'), ('session_scheduled', 'Séance Programmée'), ('session_modified', 'Séance Modifiée'), ('session_cancelled', 'Séance Annulée'), ('exam_scheduled', 'Examen Programmé'), ('timetable_published', 'Emploi du Temps Publié'), ('timetable_updated', 'Emploi du Temps Modifié'), ('teacher_unavailable', 'Enseignant Indisponible'), ('room_changed', 'Salle Modifiée'), ('room_deactivated', 'Salle Désactivée'), ('conflict_detected', 'Conflit Détecté'), ('contact_received', 'Message Reçu'), ('association_approved', 'Association Approuvée'), ('general', 'Notification Générale')], max_length=50, verbose_name='Type'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at'], name='notificatio_created_ae6ed6_idx'),
        ),
    ]
